$(function(){
    $("#b1").mouseenter(function(){
    $("#b1").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b1").mouseleave(function(){
    $("#b1").css("background-color","white")});
});
$(function(){
    $("#b2").mouseenter(function(){
    $("#b2").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b2").mouseleave(function(){
    $("#b2").css("background-color","white")});
});
$(function(){
    $("#b3").mouseenter(function(){
    $("#b3").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b3").mouseleave(function(){
    $("#b3").css("background-color","white")});
});
$(function(){
    $("#b4").mouseenter(function(){
    $("#b4").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b4").mouseleave(function(){
    $("#b4").css("background-color","white")});
});
$(function(){
    $("#b5").mouseenter(function(){
    $("#b5").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b5").mouseleave(function(){
    $("#b5").css("background-color","white")});
});
$(function(){
    $("#b6").mouseenter(function(){
    $("#b6").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b6").mouseleave(function(){
    $("#b6").css("background-color","white")});
});
$(function(){
    $("#b7").mouseenter(function(){
    $("#b7").css("background-color","#3F5FEC")});
});
$(function(){
    $("#b7").mouseleave(function(){
    $("#b7").css("background-color","white")});
});



